version: '2'
services:
  lifestudiesapp6-app:
    image: lifestudiesapp6
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lifestudiesapp6-postgresql:5432/LifestudiesApp6
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://lifestudiesapp6-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://lifestudiesapp6-elasticsearch:9200
    ports:
      - 8080:8080
  lifestudiesapp6-postgresql:
    extends:
      file: postgresql.yml
      service: lifestudiesapp6-postgresql
  lifestudiesapp6-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: lifestudiesapp6-elasticsearch
